app/models.py
from typing import Optional, List
import sqlalchemy as sa
import sqlalchemy.orm as so
from app import db

pokemon_types = sa.Table("pokemon_types", 
db.metadata, 
sa.Column("pokemon_id", sa.ForeignKey("pokemon.id"), primary_key=True),
sa.Column("type_id", sa.ForeignKey("type.id"), primary_key=True),
)

pokemon_weaknesses = sa.Table("pokemon_weaknesses", 
db.metadata, 
sa.Column("pokemon_id", sa.ForeignKey("pokemon.id"), primary_key=True),
sa.Column("weakness_id", sa.ForeignKey("weakness.id"), primary_key=True),
)

class Type(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    name: so.Mapped[str] = so.mapped_column(sa.String(32), unique=True)

class Weakness(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    name: so.Mapped[str] = so.mapped_column(sa.String(32), unique=True)

class NextEvolution(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    num: so.Mapped[str] = so.mapped_column(sa.String(3))
    name: so.Mapped[str] = so.mapped_column(sa.String(64))

    pokemon_id: so.Mapped[int] = so.mapped_column(sa.ForeignKey("pokemon.id"))
    pokemon: so.Mapped["Pokemon"] = so.relationship(back_populates="next_evolution")

class Pokemon(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    num: so.Mapped[str] = so.mapped_column(sa.String(3), unique=True)
    name: so.Mapped[str] = so.mapped_column(sa.String(64), unique=True)
    img: so.Mapped[str] = so.mapped_column(sa.String(120), unique=True)
    types: so.Mapped[List["Type"]] = so.relationship(secondary=pokemon_types, backref="pokemons")
    height: so.Mapped[str] = so.mapped_column(sa.String(64))
    weight: so.Mapped[str] = so.mapped_column(sa.String(64))
    weaknesses: so.Mapped[List["Weakness"]] = so.relationship(secondary=pokemon_weaknesses, backref="pokemons")
    next_evolution: so.Mapped[List["NextEvolution"]] = so.relationship(back_populates="pokemon", cascade="all, delete-orphan")

    def __repr__(self):
        return f'<Pokemon {self.name}>'

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap5

db = SQLAlchemy()
migrate = Migrate()

def create_app(config_class=Config):
    app = Flask(__name__)
    bootstrap = Bootstrap5(app)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)

    from app.routes import bp as main_bp
    app.register_blueprint(main_bp)
    
    from app import routes, models

    return app

app/routes.py
from flask import Blueprint, render_template
from app.models import Pokemon

bp = Blueprint('main', __name__)

type_colors = {
    "Normal": "#A8A77A",
    "Fire": "#EE8130",
    "Water": "#6390F0",
    "Electric": "#F7D02C",
    "Grass": "#7AC74C",
    "Ice": "#96D9D6",
    "Fighting": "#C22E28",
    "Poison": "#A33EA1",
    "Ground": "#E2BF65",
    "Flying": "#A98FF3",
    "Psychic": "#F95587",
    "Bug": "#A6B91A",
    "Rock": "#B6A136",
    "Ghost": "#735797",
    "Dragon": "#6F35FC",
    "Dark": "#705746",
    "Steel": "#B7B7CE",
    "Fairy": "#D685AD"
}

@bp.route("/")
def index():
    return render_template('index.html')

@bp.route("/pokemon/<pokemonname>", methods=["GET"])
def show_pokemon(pokemonname):
    results = Pokemon.query.filter(Pokemon.name.ilike(pokemonname)).all()

    if not results:
        return render_template('pokemonnotfound.html', pokemonname=pokemonname)

    return render_template('pokemonflaskapi.html', pokemonname=pokemonname, pokemon=results, type_colors=type_colors)

app/templates/base.html
<!doctype html>
<html>
  <head>
    {% block head %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.cdnfonts.com/css/pokemon-solid" rel="stylesheet">

    {% block styles %}
        <!-- Bootstrap CSS -->
        {{ bootstrap.load_css() }}
    {% endblock %}

    {% if title %}
    <title>{{ title }} - Pokémon Flask API</title>
    {% else %}
    <title>Welcome to Pokémon Flask API</title>
    {% endif %}
    {% endblock %}
  </head>
  <body style="background-color:tomato;">
    {% from 'bootstrap5/nav.html' import render_nav_item %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="navbar-nav mr-auto">
        <a class="navbar-brand">
          Pokémon Flask API:
        </a>
        {{ render_nav_item('main.index', 'Home') }}
      </div>
    </nav>
    {% block content %}
    {% endblock %}
    {% block scripts %}
      <!-- Optional JavaScript -->
      {{ bootstrap.load_js() }}
    {% endblock %}
  </body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
    <br />
    <h1 class="text-center" style="color: #ffee00; font-family: 'Pokemon Solid', sans-serif;">Pokémon Flask API: </h1>
    <h2 class="text-center text-white">An API That Showcases The Original 150 Pokémon!</h2>
    <br />
    <h3 class="text-center">Search For A Pokémon:</h3>
    <form class="text-center" action="{{ url_for('main.show_pokemon', pokemonname='')}}" method="get" onsubmit="event.preventDefault(); 
        const name = document.getElementById('pokemon_input').value.trim().toLowerCase();
        if (name) {
            window.location.href = '/pokemon/' + encodeURIComponent(name);
        }"
    >
        <input type="text" id="pokemon_input" name="pokemonname" placeholder="Enter Pokémon name" required/>
        <button class="btn btn-primary" type="submit">Search</button>
    </form>
{% endblock %}

app/templates/pokemonflaskapi.html
{% extends "base.html" %}

{% block content %}
   <h1 class="text-center">Pokedex Entry:</h1>
   <!-- Loop through the single array of only one element inside it: -->
   {% for item in pokemon %}
   <div class="d-flex justify-content-center my-4">
      <div class="card bg-primary" style="width: 18rem;">
         <img class="card-img-top w-50 mx-auto" src='{{ item.img }}' alt="Card image cap"/>
         <div class="card-body text-center">
            <h2 class="card-title">{{item.name}} #{{ item.num }}</h2>
         </div>
         <ul class="list-group list-group-flush">
            <li class="list-group-item bg-warning">
               <h5>Types: </h5>
               <ul>
               {% for type in item.types %}
               <li>
                  <span class="badge text-light"
                        style="background-color: {{ type_colors.get(type.name, 'gray') }};">
                     {{ type.name }}
                  </span>
               </li>
               {% endfor %}
               </ul>
            </li>
            <li class="list-group-item bg-warning">
               <h5>Height: {{ item.height }}</h5>
            </li>
            <li class="list-group-item bg-warning">
            <h5>Weight: {{ item.weight }}</h5>
            </li>
            <li class="list-group-item bg-warning">
               <h5>Weaknesses: </h5>
               <ul>
               {% for weakness in item.weaknesses %}
                  <li>
                     <span class="badge text-light"
                           style="background-color: {{ type_colors.get(weakness.name, 'gray') }};">
                        {{ weakness.name }}
                     </span>
                  </li>
               {% endfor %}
               </ul>
            </li>
            {% if item.next_evolution %}
            <li class="list-group-item bg-warning">
               <h5>Evolutions: </h5>
               <ul>
               {% for evo in item.next_evolution %}
               <li>Number: {{ evo["num"] }}</li>
               <li>Name: <a href="/pokemon/{{ evo['name'] }}">{{ evo["name"] }}</a></li>
               {% endfor %}
               </ul>
            </li>
            {% endif %}
         </ul>
      </div>
   </div>
   {% endfor %}
{% endblock %}

app/templates/pokemonnotfound.html
{% extends "base.html" %}

{% block content %}
<div>
    No Pokemon found with name: {{ pokemonname }}
</div>
{% endblock %}